report:
  script:
    - echo "done"
  artifacts:
    reports:
      junit: ./qa/**/junit_rspec.xml
    paths:
      - ./qa

report-2:
  script:
    - echo "done"
  artifacts:
    reports:
      junit: junit_rspec.xml
