review_app_bug:
  stage: test
  script:
    - echo "deployed"
  environment:
    name: review_bug
    on_stop: stop_review_app_bug

stop_review_app_bug:
  stage: test
  script:
    - echo "stopped"
  when: manual
  environment:
    name: review_bug
    action: stop

review_app_doc:
  stage: deploy
  script:
    - echo "deployed"
  environment:
    name: review_doc
    on_stop: stop_review_app_doc

stop_review_app_doc:
  stage: deploy
  script:
    - echo "stopped"
  when: manual
  environment:
    name: review_doc
    action: stop
    